import { useEffect, useState, type FormEvent } from "react";
import { Notice, PageHero } from "../components/Layout";
import { demoSolutions } from "../data/demoSolutions";
import { repository } from "../data/repository";
import type { AideDraft, SolutionRecord } from "../domain/model";
import { aideMarkdown, download, markdownDocx } from "../lib/exports";

const helpTypes=["Early consultation","Prototype boundary question","Data or risk guidance","Resource or ownership question","IPPM routing advice","Preparing for production","Significant change","Closure or retirement advice"];
export function AideIntakePage(){const [solutions,setSolutions]=useState<SolutionRecord[]>(demoSolutions),[solutionId,setSolutionId]=useState(""),[helpType,setHelpType]=useState(helpTypes[0]),[changed,setChanged]=useState(""),[questions,setQuestions]=useState(""),[message,setMessage]=useState("");useEffect(()=>{repository.listSolutions().then(x=>setSolutions([...demoSolutions,...x]))},[]);const selected=solutions.find(x=>x.id===solutionId);const draft=():AideDraft=>({schemaVersion:1,id:`aide-${solutionId}`,solutionId,helpType,changedInformation:changed,questions,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const save=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;try{await repository.saveAideDraft(draft());setMessage("Review-package draft saved locally. No institutional transmission occurred.")}catch{setMessage("The draft could not be saved. Check browser storage and try again.")}};const md=()=>selected?aideMarkdown(selected,draft()):"";return <><PageHero eyebrow="Local preparation tool" title="Prepare an AIDE review package"><p>AIDE provides advice and documented recommendations. Exporting a package is not submission.</p></PageHero><section className="container-page section narrow"><Notice/><form onSubmit={save}><label>Select an inventory record<select required value={solutionId} onChange={e=>setSolutionId(e.target.value)}><option value="">Choose a solution</option>{solutions.map(x=><option value={x.id} key={x.id}>{x.name} {x.source==="demo"?"(demo)":""}</option>)}</select></label>{selected&&<div className="prefill"><strong>Known information</strong><p>{selected.summary}</p><dl><div><dt>Owner</dt><dd>{selected.owner}</dd></div><div><dt>Stage</dt><dd>{selected.lifecycleStage}</dd></div><div><dt>Route</dt><dd>{selected.governanceRoute}</dd></div></dl></div>}<label>Type of help requested<select value={helpType} onChange={e=>setHelpType(e.target.value)}>{helpTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>What is missing or has changed?<textarea value={changed} onChange={e=>setChanged(e.target.value)}/></label><label>Questions for the AIDE Committee<textarea value={questions} onChange={e=>setQuestions(e.target.value)}/></label><button className="button primary">Save browser-local draft</button></form><p role="status">{message}</p>{selected&&<div className="actions"><button className="button secondary" onClick={()=>download(new Blob([md()],{type:"text/markdown"}),"aide-review-package.md")}>Export Markdown</button><button className="button secondary" onClick={async()=>download(await markdownDocx(md()),"aide-review-package.docx")}>Export Word (.docx)</button></div>}</section></>}
