import { Link } from "react-router-dom";
import { PageHero } from "../components/Layout";
import { ProcessExplorer } from "../components/ProcessExplorer";
import { aideRecommendations, processStages, routes } from "../domain/content";

export function ProcessPage() { return <><PageHero eyebrow="The York AI development process" title="See the whole path."><p>Explore the main sequence, optional consultations and conditional routes. Select any point for its purpose, actions and next tool.</p></PageHero><section className="container-page section process-section"><div className="section-heading"><p className="eyebrow">Interactive process</p><h2>Move through—or jump in.</h2><p>The red path shows how far the selected point sits along the primary sequence. Optional routes can be used when they fit; they are not automatic gates.</p></div><ProcessExplorer/><aside className="decision"><strong>Decision log · confirmation required</strong><p>York must confirm the accountable production decision role and whether Change Management selects or verifies operational ownership.</p></aside></section><section className="band"><div className="container-page"><div className="section-heading"><p className="eyebrow">Stage overview</p><h2>Six stages to revisit.</h2></div><ol className="stage-list">{processStages.map(s=><li key={s.stage}><div><span className="eyebrow">{s.stage}</span><h2>{s.title}</h2><p>{s.body}</p></div><ul>{s.actions.map(a=><li key={a}>{a}</li>)}</ul></li>)}</ol></div></section></>; }
export function MarsPage() { return <><PageHero eyebrow="One development path" title="Build with MARS"><p>MARS is a supported platform for specific AI solutions—not the umbrella governance process.</p></PageHero><section className="container-page section narrow"><h2>Before you build</h2><ol><li>Define the problem and search the AI Solutions Inventory.</li><li>Create or update a lightweight solution record.</li><li>Complete current MARS platform prerequisites.</li><li>Prototype only within <strong>Interim guidance</strong>; approved prototype guardrails are still to be confirmed.</li><li>Reassess if data, users, integrations, cost, risk or production intent changes.</li></ol><p><Link className="button primary" to={routes.ideation}>Open the Ideation Guide</Link></p></section></>; }
export function AidePage() { return <><PageHero eyebrow="Advisory review" title="AIDE Committee"><p>Sponsored by the Office of the CIO, AIDE reviews information and provides documented recommendations. It does not approve, authorize, reject, stop, fund or deploy solutions.</p></PageHero><section className="container-page section two-col"><div><h2>What AIDE may recommend</h2><ul className="check-list">{aideRecommendations.map(x=><li key={x}>{x}</li>)}</ul></div><div><h2>Routes stay open</h2><p>Consult early or when a trigger emerges. AIDE may recommend referral to IPPM. IPPM may refer York-developed AI work to AIDE. You may approach IPPM directly; AIDE is not the exclusive gateway.</p><AideIntakeLink /></div></section></>; }
function AideIntakeLink(){ return <Link className="button primary" to="/aide-intake">Prepare a local review package</Link> }
export function ProductionPage() { return <><PageHero eyebrow="Working production gate" title="Preparing for production"><p>Guidance only. This page does not collect evidence, approve production or submit a Change Request.</p></PageHero><section className="container-page section two-col"><div><h2>What to prepare</h2><ul><li>A named operational owner and an accepted support model</li><li>Current scope, users, data, integrations, costs and risks</li><li>Specialist reviews identified for privacy, security, accessibility, architecture, procurement, legal or data concerns</li><li>A current inventory record and relevant AIDE recommendations</li></ul></div><div className="decision"><h2>Decision still needed</h2><p>Change Management review is the current working final production gate. York must confirm the accountable production decision role and whether Change Management selects or verifies operational ownership. Change Management does not provide ongoing support.</p></div></section></>; }
export function ResourcesPage() { return <><PageHero eyebrow="People, platforms and funding" title="York resources"><p>Match the need to a route. Resourcing and implementation change approval are separate decisions.</p></PageHero><section className="container-page section card-grid"><article><h2>Specialist advice</h2><p>Privacy, security, accessibility, architecture, procurement, legal and data reviews may be conditionally identified.</p></article><article><h2>IPPM</h2><p>Approach IPPM directly for relevant portfolio or project support. AIDE can recommend IPPM, and IPPM can refer AI work to AIDE. A resource request does not automatically become an initiative.</p></article><article><h2>AIDE Committee</h2><p>Ask for advisory guidance on boundaries, ownership, risk, resourcing or routing.</p></article></section></>; }
