import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Notice, PageHero } from "../components/Layout";
import { SolutionForm } from "../components/SolutionForm";
import { demoSolutions } from "../data/demoSolutions";
import { repository } from "../data/repository";
import { blankSolution, lifecycleStages, type SolutionRecord } from "../domain/model";

export function InventoryPage(){ const [records,setRecords]=useState<SolutionRecord[]>([]),[query,setQuery]=useState(""),[life,setLife]=useState(""),[editing,setEditing]=useState<SolutionRecord|null>(null),[state,setState]=useState("Loading browser-local records…");
  const load=()=>repository.listSolutions().then(r=>{setRecords([...demoSolutions,...r]);setState("")}).catch(()=>setState("Could not load browser-local records.")); useEffect(()=>{void load()},[]);
  const shown=useMemo(()=>records.filter(r=>(!life||r.lifecycleStage===life)&&[r.name,r.summary,r.problem,r.unit,r.platform].join(" ").toLowerCase().includes(query.toLowerCase())),[records,query,life]);
  const save=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;try{await repository.saveSolution({...editing,relatedWork:Array.isArray(editing.relatedWork)?editing.relatedWork:String(editing.relatedWork).split(",").map(x=>x.trim()).filter(Boolean)});setState("Draft saved in this browser.");setEditing(null);load()}catch{setState("Save failed. Check browser storage and try again.")}};
  return <><PageHero eyebrow="Search, reuse and connect" title="AI Solutions Inventory"><p>A prototype inventory for York-developed AI solutions across platforms.</p></PageHero><section className="container-page section"><div className="demo-label"><strong>Demonstration data</strong> is illustrative and is not authoritative York information.</div><Notice/><div className="toolbar"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, need, unit or platform"/></label><label>Lifecycle<select value={life} onChange={e=>setLife(e.target.value)}><option value="">All stages</option>{lifecycleStages.map(x=><option key={x}>{x}</option>)}</select></label><button className="button primary" onClick={()=>setEditing(blankSolution())}>Create prototype record</button><button className="button secondary" onClick={async()=>{if(confirm("Delete your browser-local prototype records? Demonstration examples will remain.")){await repository.resetUserData();load()}}}>Reset demo data</button></div><p role="status" aria-live="polite">{state}</p>{editing&&<div className="editor"><div className="section-heading"><h2>{editing.name?"Update solution":"Create a solution"}</h2><button onClick={()=>setEditing(null)}>Cancel</button></div><SolutionForm record={editing} onChange={setEditing} onSave={save}/></div>}<div className="inventory-grid">{shown.map(r=><article key={r.id}><span className="source">{r.source==="demo"?"Demo record":"Browser-local record"}</span><h2>{r.name}</h2><p>{r.summary}</p><dl><div><dt>Lifecycle</dt><dd>{r.lifecycleStage}</dd></div><div><dt>Review</dt><dd>{r.reviewState}</dd></div><div><dt>Route</dt><dd>{r.governanceRoute}</dd></div><div><dt>Disposition</dt><dd>{r.disposition}</dd></div><div><dt>Service</dt><dd>{r.serviceState}</dd></div></dl>{r.relatedWork.length>0&&<p><strong>Related:</strong> {r.relatedWork.map(id=>records.find(x=>x.id===id)?.name||id).join(", ")}</p>}{r.source==="user"&&<button className="text-button" onClick={()=>setEditing(r)}>Update this record →</button>}</article>)}</div>{!state&&shown.length===0&&<div className="empty"><h2>No solutions found</h2><p>Try broader keywords, clear the lifecycle filter, or create a prototype record.</p></div>}</section></> }
