import { GuidedForm } from "../components/GuidedForm";
import { productionReadinessGuideSections } from "../data/guides";
import {
  downloadBlob,
  generateAnswersSnapshotDocx,
  generateAnswersSnapshotMarkdown,
  generateCompletedGuideMarkdown,
  generateProductionReadinessDocx,
  slugify,
} from "../lib/guideExport";

export function ProductionReadinessGuidePage() {
  return (
    <GuidedForm
      storageKey="mars-production-guide-v1"
      eyebrow="Production"
      title="Production Readiness Guide"
      intro="A coached walkthrough of the same requirements as the Production Readiness Checklist. Answer each prompt in your own words and generate a York-branded document ready to attach to your production request."
      backLink={{ label: "Back to the Production Readiness Checklist", href: "/production" }}
      sections={productionReadinessGuideSections}
      quickExportHelp="Your answers are also autosaved to this browser as you go, but you can export a backup snapshot at any point, in either format, even if you haven't finished every question."
      quickExports={[
        {
          label: "Export progress (.md)",
          onExport: (answers) => {
            const slug = slugify(answers.solutionName?.trim() || "production-readiness-draft", "production-readiness-draft");
            const markdown = generateAnswersSnapshotMarkdown(
              "Production Readiness Guide",
              productionReadinessGuideSections,
              answers,
            );
            downloadBlob(new Blob([markdown], { type: "text/markdown;charset=utf-8" }), `${slug}-production-readiness-draft.md`);
          },
        },
        {
          label: "Export progress (.docx)",
          onExport: async (answers) => {
            const slug = slugify(answers.solutionName?.trim() || "production-readiness-draft", "production-readiness-draft");
            const blob = await generateAnswersSnapshotDocx(
              "Production Readiness Guide",
              productionReadinessGuideSections,
              answers,
            );
            downloadBlob(blob, `${slug}-production-readiness-draft.docx`);
          },
        },
      ]}
      completeActions={[
        {
          label: "Generate Word document",
          help: "Downloads a .docx file with your answers templated into a York-branded production request document.",
          primary: true,
          onClick: async (answers) => {
            const blob = await generateProductionReadinessDocx(productionReadinessGuideSections, answers);
            const nameSlug = slugify(answers.solutionName?.trim() || "production-readiness", "production-readiness");
            downloadBlob(blob, `${nameSlug}-production-readiness-request.docx`);
          },
        },
        {
          label: "Generate Markdown file",
          help: "Downloads a .md file with the same completed answers, useful for pasting into other tools.",
          onClick: (answers) => {
            const nameSlug = slugify(answers.solutionName?.trim() || "production-readiness", "production-readiness");
            const markdown = generateCompletedGuideMarkdown(
              `${answers.solutionName?.trim() || "Untitled solution"}: Production Readiness Request`,
              productionReadinessGuideSections,
              answers,
              "Generated by the MARS Production Readiness Guide. Review and edit before submitting for governance review.",
            );
            downloadBlob(new Blob([markdown], { type: "text/markdown;charset=utf-8" }), `${nameSlug}-production-readiness-request.md`);
          },
        },
      ]}
    />
  );
}
