export type UserStage = "idea" | "search" | "prepare" | "prototype" | "resources" | "production" | "change" | "close";
export interface RoutingAnswers { stage: UserStage; sensitive?: boolean; peopleDecisions?: boolean; institutional?: boolean; integrations?: boolean; materialResources?: boolean; unclearOwner?: boolean; outsideGuidance?: boolean; majorChange?: boolean }
export interface RouteResult { title: string; why: string; requirement: "Required" | "Optional"; prepare: string[]; href: string }

export function getNextStep(a: RoutingAnswers): RouteResult {
  if (a.stage === "production" || a.institutional) return { title: "Prepare for Change Management review", why: "Production or institutional use requires the applicable production process and an accepted operational owner and support model.", requirement: "Required", prepare: ["Current solution record", "Operational owner and support model", "Relevant specialist review outcomes"], href: "/preparing-for-production" };
  if (a.sensitive || a.peopleDecisions || a.integrations || a.outsideGuidance || (a.stage === "change" && a.majorChange)) return { title: "Consult the AIDE Committee", why: "The data, impact, access, boundary or change signals indicate that documented advice and possible specialist referrals are appropriate.", requirement: "Required", prepare: ["Problem and intended outcome", "Data and integration details", "Known risks and proposed controls"], href: "/aide-committee" };
  if (a.stage === "resources" && a.materialResources) return { title: "Choose a resourcing route", why: "Material funding, staffing, procurement or recurring costs need a resourcing conversation. AIDE can advise and may recommend IPPM, but you may also approach IPPM directly.", requirement: "Optional", prepare: ["Resource estimate", "Ownership and value", "Costs and dependencies"], href: "/resources" };
  if (a.stage === "search") return { title: "Search and reuse existing work", why: "Starting with existing solutions can avoid duplication and reveal collaborators.", requirement: "Optional", prepare: ["Need and keywords", "Unit and intended users"], href: "/inventory" };
  if (a.stage === "close") return { title: "Plan closure or retirement", why: "Owners should address users, data, integrations, support and inventory status before closing work.", requirement: "Required", prepare: ["Owner", "User and data impacts", "Retirement plan"], href: "/process" };
  if (a.unclearOwner) return { title: "Clarify ownership and support", why: "A viable solution needs a named owner and credible support model before production planning.", requirement: "Required", prepare: ["Potential owner", "Support needs", "Expected users and service level"], href: "/aide-committee" };
  return { title: "Continue within interim prototype guidance", why: "No elevated trigger was identified. AIDE consultation remains available at any time.", requirement: "Optional", prepare: ["Inventory entry", "Prototype boundaries", "Success measures"], href: "/ideation-guide" };
}
