import type { FormEvent } from "react";
import { dispositions, governanceRoutes, lifecycleStages, reviewStates, serviceStates, type SolutionRecord } from "../domain/model";

export function SolutionForm({record,onChange,onSave,saveLabel="Save browser-local draft"}:{record:SolutionRecord;onChange:(r:SolutionRecord)=>void;onSave:(e:FormEvent)=>void;saveLabel?:string}) {
  const set=(key:keyof SolutionRecord,value:string)=>onChange({...record,[key]:value});
  const text=(key:keyof SolutionRecord,label:string,required=false)=><label>{label}{required&&<span aria-hidden="true"> *</span>}<input required={required} value={String(record[key])} onChange={e=>set(key,e.target.value)}/></label>;
  const area=(key:keyof SolutionRecord,label:string,required=false)=><label>{label}{required&&<span aria-hidden="true"> *</span>}<textarea required={required} value={String(record[key])} onChange={e=>set(key,e.target.value)}/></label>;
  const select=(key:keyof SolutionRecord,label:string,values:readonly string[])=><label>{label}<select value={String(record[key])} onChange={e=>set(key,e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
  return <form onSubmit={onSave}><fieldset><legend>Need and value</legend><div className="form-grid">{text("name","Solution name",true)}{area("summary","Plain-language summary",true)}{area("problem","Problem or need",true)}{area("intendedOutcome","Intended outcome",true)}{area("intendedUsers","People affected and intended users")}{area("relatedWork","Related existing work (IDs)")}</div></fieldset><fieldset><legend>Delivery</legend><div className="form-grid">{text("unit","York unit",true)}{text("owner","Owner or contact",true)}{text("collaborators","Collaborators")}{text("platform","Platform")}{area("marsDetails","MARS-specific details, if applicable")}{area("supportModel","Ownership and support model")}{area("costs","Costs")}{area("successMeasures","Success measures")}</div></fieldset><fieldset><legend>Risk and change</legend><div className="form-grid">{area("dataConsiderations","Data considerations")}{area("integrations","Integrations")}{area("resourceNeeds","Resource needs")}{area("risks","Risks")}{area("currentConditions","Current conditions")}{area("nextAction","Next action")}</div></fieldset><fieldset><legend>Separate status dimensions</legend><div className="form-grid">{select("lifecycleStage","Lifecycle stage",lifecycleStages)}{select("reviewState","Review state",reviewStates)}{select("governanceRoute","Governance route",governanceRoutes)}{select("disposition","Disposition",dispositions)}{select("serviceState","Service state",serviceStates)}</div></fieldset><button className="button primary" type="submit">{saveLabel}</button></form>;
}
