import type { FormEvent } from "react";
import { dispositions, governanceRoutes, lifecycleStages, reviewStates, serviceStates, type SolutionRecord } from "../domain/model";

export function SolutionForm({record,onChange,onSave,saveLabel="Save browser-local draft",activeStep}:{record:SolutionRecord;onChange:(r:SolutionRecord)=>void;onSave:(e:FormEvent)=>void;saveLabel?:string;activeStep?:number}) {
  const set=(key:keyof SolutionRecord,value:string)=>onChange({...record,[key]:value});
  const text=(key:keyof SolutionRecord,label:string,required=false)=><label>{label}{required&&<span aria-hidden="true"> *</span>}<input required={required} value={String(record[key])} onChange={e=>set(key,e.target.value)}/></label>;
  const area=(key:keyof SolutionRecord,label:string,required=false)=><label>{label}{required&&<span aria-hidden="true"> *</span>}<textarea required={required} value={String(record[key])} onChange={e=>set(key,e.target.value)}/></label>;
  const select=(key:keyof SolutionRecord,label:string,values:readonly string[])=><label>{label}<select value={String(record[key])} onChange={e=>set(key,e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
  const visible=(step:number)=>activeStep === undefined || activeStep === step;
  return <form onSubmit={onSave}><fieldset hidden={!visible(0)}><legend>Need and value</legend><p className="field-help">Begin with the problem, people affected and current alternative. Describe value before implementation.</p><div className="form-grid">{text("name","Solution name",true)}{area("summary","Plain-language summary",true)}{area("problem","Problem, current alternative and people affected",true)}{area("intendedOutcome","Intended outcome and value",true)}{area("intendedUsers","Intended users")}{area("relatedWork","Related existing work (IDs)")}</div></fieldset><fieldset hidden={!visible(1)}><legend>Path and ownership</legend><p className="field-help">Choose a path only after shaping the need. Make ownership and support explicit.</p><div className="form-grid">{text("unit","York unit",true)}{text("owner","Owner or contact",true)}{text("collaborators","Collaborators")}{text("platform","Platform")}{area("marsDetails","MARS-specific details, if applicable")}{area("supportModel","Ownership and support model")}{area("costs","Costs")}{area("successMeasures","Success measures")}</div></fieldset><fieldset hidden={!visible(2)}><legend>Risk and change</legend><p className="field-help">Do not enter sensitive or confidential information. Describe categories and considerations only.</p><div className="form-grid">{area("dataConsiderations","Data considerations")}{area("integrations","Integrations")}{area("resourceNeeds","Resource needs")}{area("risks","Risks")}{area("currentConditions","Current conditions")}{area("nextAction","Next action")}</div></fieldset><fieldset hidden={!visible(3)}><legend>Review the status</legend><p className="field-help">Keep each dimension separate so that, for example, a prototype can be active while conditions remain open.</p><div className="form-grid">{select("lifecycleStage","Lifecycle stage",lifecycleStages)}{select("reviewState","Review state",reviewStates)}{select("governanceRoute","Governance route",governanceRoutes)}{select("disposition","Disposition",dispositions)}{select("serviceState","Service state",serviceStates)}</div></fieldset>{activeStep === undefined && <button className="button primary" type="submit">{saveLabel}</button>}{activeStep === 3 && <button className="button primary" type="submit">{saveLabel}</button>}</form>;
}
